sudo: false
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
services:
  - memcached
  - redis
script: 
  - sbt ++2.11.7 coverage test 
  - sbt ++2.11.2 test
  - sbt ++2.11.0 test
after_success: "sbt coverageAggregate coveralls"
